# docker-compose.override.yml
# This file is automatically used when running docker-compose locally
# It provides helpful debugging and testing configurations
version: '3.8'

services:
  sync:
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile

    # Resource limits for better stability
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

    # Larger shared memory for Chrome
    shm_size: '2gb'

    # Environment overrides for development
    environment:
      - DEBUG=true
      - HEADLESS=true
      # Uncomment to use FlareSolverr during testing
      # - FLARESOLVERR_URL=http://flaresolverr:8191

    # Additional volumes for debugging
    volumes:
      - ./data/_cache:/app/_cache:rw
      - ./data/logs:/app/logs:rw
      # Uncomment to mount source code for live testing (no rebuild needed)
      # - ./src:/app/src:ro
      # - ./main.py:/app/main.py:ro

    # Restart policy for development
    restart: "no"

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Optional: FlareSolverr for Cloudflare bypass during testing
  # Uncomment to enable
  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   environment:
  #     - LOG_LEVEL=info
  #     - LOG_HTML=false
  #     - CAPTCHA_SOLVER=none
  #   ports:
  #     - "8191:8191"
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"